spring.application.name=Bank
spring.datasource.url=jdbc:mysql://localhost:3306/bankingApp?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=mani
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
